-- AlterTable
ALTER TABLE "WorkPolicy" ADD COLUMN "dailyMinutes" INTEGER NOT NULL DEFAULT 480,
ADD COLUMN "overtimeAfterMinutes" INTEGER NOT NULL DEFAULT 480,
ADD COLUMN "flexInMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "flexOutMinutes" INTEGER NOT NULL DEFAULT 0;
